name       : asciinema
version    : 1.3.0
release    : 1
source     :
    - https://github.com/asciinema/asciinema/archive/v1.3.0.tar.gz : 968016828119d53b8e4e6ccf40a2635704d236f8e805f635c15adc09a4373a55
license    : GPL-3.0
component  : multimedia.video
summary    : Terminal session recorder and the best companion of asciinema.org
description: |
    Terminal session recorder and the best companion of asciinema.org
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
install    : |
    %python3_install
