name       : asciinema
version    : 2.0.0
release    : 4
source     :
    - https://github.com/asciinema/asciinema/archive/v2.0.0.tar.gz : 65224d8dcc8c579fd678fff83ea89eecfd35a1d2ca853ee6fcf27d2f7b5e3205
license    : GPL-3.0
component  : multimedia.video
summary    : Terminal session recorder and the best companion of asciinema.org
description: |
    Terminal session recorder and the best companion of asciinema.org
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
