name       : asciinema
version    : 1.4.0
release    : 2
source     :
    - https://github.com/asciinema/asciinema/archive/v1.4.0.tar.gz : 841a55b0f51988d5e155e99badbd6ce5cf3b43cca2ba15cd20c971a19719dc9a
license    : GPL-3.0
component  : multimedia.video
summary    : Terminal session recorder and the best companion of asciinema.org
description: |
    Terminal session recorder and the best companion of asciinema.org
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
install    : |
    %python3_install
