name       : asciinema
version    : 2.0.2
release    : 6
source     :
    - https://github.com/asciinema/asciinema/archive/v2.0.2.tar.gz : 2578a1b5611e5375771ef6582a6533ef8d40cdbed1ba1c87786fd23af625ab68
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Terminal session recorder and the best companion of asciinema.org
description: |
    Terminal session recorder and the best companion of asciinema.org
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
