name       : asciinema
version    : 2.0.1
release    : 5
source     :
    - https://github.com/asciinema/asciinema/archive/v2.0.1.tar.gz : 7087b247dae36d04821197bc14ebd4248049592b299c9878d8953c025ac802e4
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Terminal session recorder and the best companion of asciinema.org
description: |
    Terminal session recorder and the best companion of asciinema.org
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
